baseURL = "https://example.com"
title = "Dave Smith"
languageCode = "en-gb"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright 2021, Dave Smith"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = -100
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = -90

# Configuration Features
[params]
  description = "My occasional ramblings."      # Your meta description of the site
  header_title = "Dave Smith"                 # Your header title
  header_subtitle = "I am not a blogger" # Your header subtitle
  home_image = "/images/badge.png"          # Path to header image starting from the static directory
  recent_posts = 5                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "http://github.com/davesmith00000"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/davidjamessmith"
