addSbtPlugin("org.typelevel"       % "laika-sbt"    % "1.0.0")
addSbtPlugin("com.typesafe.sbt"    % "sbt-site"     % "1.4.1")
addSbtPlugin("com.typesafe.sbt"    % "sbt-ghpages"  % "0.6.3")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"  % "0.3.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.timushev.sbt"    % "sbt-updates"  % "0.6.4")
